export const SET_CATEGORY_FILTER = "SET_CATEGORY_FILTER";
export const CLEAR_CATEGORY_FILTER = "CLEAR_CATEGORY_FILTER";

export const SET_BRAND_FILTER = "SET_BRAND_FILTER";
export const CLEAR_BRAND_FILTER = "CLEAR_BRAND_FILTER";

export const SET_CATEGORY = "SET_CATEGORY";
export const CLEAR_CATEGORY = "CLEAR_CATEGORY";

export const SET_BRAND = "SET_BRAND";
export const CLEAR_BRAND = "CLEAR_BRAND";

export const SET_GOODS = "SET_GOODS";
export const CLEAR_GOODS = "CLEAR_GOODS";

export const SET_CART = "SET_CART";
export const CLEAR_CART = "CLEAR_CART";

export const SET_ROUTE = "SET_ROUTE";

export const SET_SEARCH = "SET_SEARCH";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const CLEAR_LAST_SEARCH = "CLEAR_LAST_SEARCH";
